"""
Barcelona TMB/other bus route destination lookup.
Maps route number → short description of endpoints/purpose.
Source: TMB route information (tmb.cat)
"""

BCN_BUS_ROUTES: dict[str, str] = {
    # Vertical (V) bus network
    "V1":  "Zona Universitària ↔ Verneda",
    "V3":  "Zona Universitària ↔ Bon Pastor",
    "V5":  "Badal ↔ Sagrera",
    "V7":  "Pl. Espanya ↔ Sagrera",
    "V9":  "Pl. Espanya ↔ Badalona",
    "V11": "Zona Universitària ↔ La Pau",
    "V13": "Av. Tibidabo ↔ Barceloneta",
    "V15": "Pl. Kennedy ↔ Pl. Catalunya",
    "V17": "Av. Tibidabo ↔ Poblenou",
    "V19": "Av. Tibidabo ↔ Verneda",
    "V21": "Zona Universitària ↔ Sant Adrià",
    "V23": "Sarrià ↔ Glòries",
    "V25": "Les Corts ↔ Glòries",
    "V27": "Sants ↔ Navas",
    "V29": "Pl. Espanya ↔ Clot",

    # Horizontal (H) bus network
    "H2":  "Aeroport ↔ Fòrum",
    "H4":  "Montbau ↔ Fòrum",
    "H6":  "Tibidabo ↔ Fòrum (via Gràcia)",
    "H8":  "Guinardó ↔ Pg. de Gràcia",
    "H10": "Cornellà ↔ Glòries",
    "H12": "Zona Universitària ↔ La Pau",
    "H14": "Pl. Espanya ↔ Badalona",
    "H16": "Zona Universitària ↔ Llefià",

    # Night buses (N)
    "N0":  "Pl. Catalunya ↔ Cornellà (night)",
    "N1":  "Pl. Catalunya ↔ Barberà (night)",
    "N2":  "Pl. Catalunya ↔ Gavà (night)",
    "N3":  "Pl. Catalunya ↔ Viladecans (night)",
    "N4":  "Pl. Catalunya ↔ Prat (night)",
    "N5":  "Pl. Catalunya ↔ Tibidabo (night)",
    "N6":  "Pl. Catalunya ↔ Mollet (night)",
    "N7":  "Pl. Catalunya ↔ Granollers (night)",
    "N8":  "Pl. Catalunya ↔ Gavà-Viladecans (night)",
    "N9":  "Pl. Catalunya ↔ Badalona (night)",
    "N10": "Pl. Catalunya ↔ Mataró (night)",
    "N11": "Pl. Catalunya ↔ Montgat (night)",
    "N12": "Pl. Catalunya ↔ Sant Just (night)",
    "N17": "Pl. Catalunya ↔ Sarrià (night)",
    "N24": "Pl. Catalunya ↔ Sarrià/Tibidabo (night)",
    "N27": "Pg. Gràcia ↔ L'Hospitalet (night)",

    # Conventional routes (100-series)
    "100": "Gràcia ↔ Zona Universitària",
    "101": "Sarrià ↔ Eixample",
    "102": "Pl. Francesc Macià ↔ Pl. Molina",
    "106": "Gràcia ↔ La Bonanova",
    "111": "Passeig de Gràcia ↔ Horta",
    "113": "Pl. Catalunya ↔ Horta",
    "114": "Pl. Catalunya ↔ Carmel",
    "116": "Pl. Virreina ↔ Trinitat Nova",
    "119": "Sarrià ↔ Pl. España",
    "123": "Pl. Catalunya ↔ Sarrià (via Pl. Kennedy)",
    "124": "Pl. Kennedy ↔ Castellbisbal",
    "125": "Pl. Catalunya ↔ Vallvidrera",
    "126": "Pl. Catalunya ↔ Valldoreix",
    "127": "Pl. Catalunya ↔ Sant Cugat",
    "130": "Tibidabo (funicular connection)",
    "131": "Tibidabo ↔ Gràcia",
    "132": "Pl. Kennedy ↔ Pl. Espanya",
    "133": "Sarrià ↔ Av. Príncep d'Astúries",
    "136": "Paral·lel ↔ Zona Franca",
    "141": "Hospital Sant Pau ↔ Pl. Espanya",
    "150": "Parc Güell ↔ Barceloneta",
    "154": "Gràcia ↔ Nou Barris",
    "155": "Pl. Francesc Macià ↔ Nou Barris",
    "157": "Cornellà ↔ Sants",
    "158": "Pl. Espanya ↔ El Prat",
    "170": "Gràcia ↔ Putxet",
    "174": "Gràcia ↔ Pl. Molina",
    "175": "Pl. Virreina ↔ Horta",
    "176": "Gràcia ↔ Sant Adrià",
    "180": "Paral·lel ↔ Verneda",
    "181": "Eixample ↔ Vallbona",
    "192": "Pg. Gràcia ↔ Barceloneta",
    "196": "Sarrià ↔ Pg. de Gràcia",

    # Sarrià / Sant Gervasi area specifics
    "60":  "Sarrià ↔ Eixample",
    "64":  "Sarrià ↔ Pl. Catalunya",
    "66":  "Sarrià ↔ Pg. Gràcia",
    "68":  "Av. Tibidabo ↔ Pl. Espanya",
    "70":  "Sarrià ↔ Les Corts",
    "72":  "Sarrià ↔ Pg. Gràcia",
    "74":  "Sarrià ↔ Barceloneta",
    "75":  "Pl. Kennedy ↔ Besòs",
    "76":  "Gràcia ↔ Tibidabo",
    "78":  "Pl. Kennedy ↔ Badalona",
    "22":  "Pl. Espanya ↔ Poblenou",
    "24":  "Pl. Virreina ↔ Besòs",
    "27":  "Sants ↔ Trinitat Vella",
    "32":  "Pl. Catalunya ↔ Can Dragó",
    "33":  "Pl. Catalunya ↔ Sant Andreu",
    "34":  "Diagonal ↔ Trinitat Vella",
    "36":  "Pl. Espanya ↔ Trinitat Vella",
    "37":  "Gràcia ↔ Guineueta",
    "38":  "Drassanes ↔ Zona Alta",
    "39":  "Pl. Catalunya ↔ Horta",
    "40":  "Pl. Catalunya ↔ Carmel",
    "41":  "Pg. Gràcia ↔ Tibidabo area",
    "42":  "Pg. Gràcia ↔ Canyelles",
    "43":  "Barceloneta ↔ Horta",
    "44":  "Pl. Urquinaona ↔ Penitents",
    "45":  "Pg. Gràcia ↔ Montbau",
    "46":  "Pg. Gràcia ↔ Torre Baró",
    "47":  "Ronda Universitat ↔ Trinitat Nova",
    "50":  "Pl. Catalunya ↔ Cornellà",
    "51":  "Pl. Espanya ↔ Montbau",
    "52":  "Pl. Catalunya ↔ Aerop. T2/T3",
}


def route_description(route: str) -> str | None:
    """Return destination description for a BCN bus route number, or None if unknown."""
    return BCN_BUS_ROUTES.get(route.upper().strip())
