import { NarrativeData } from '../types/analysis';

interface Props {
  narrative: NarrativeData;
  grade: string;
  composite: number;
}

const GRADE_COLORS: Record<string, string> = {
  'Excellent buy':          'bg-emerald-500',
  'Good buy':               'bg-green-500',
  'Proceed with caution':   'bg-amber-500',
  'High risk — reconsider': 'bg-red-500',
};

export default function NarrativeCard({ narrative, grade, composite }: Props) {
  const badgeColor = GRADE_COLORS[grade] ?? 'bg-slate-500';

  return (
    <div className="bg-slate-800 border border-slate-700 rounded-2xl p-6 space-y-5">
      {/* Header */}
      <div className="flex items-start justify-between gap-4">
        <div className="flex-1">
          <p className="text-xs text-slate-400 mb-1">AI Verdict</p>
          <h2 className="text-xl font-semibold text-white leading-snug">
            {narrative.verdict}
          </h2>
        </div>
        <div className="flex flex-col items-center shrink-0">
          <span className="text-4xl font-bold text-white">{composite}</span>
          <span className={`text-xs font-medium text-white px-3 py-1 rounded-full mt-1 ${badgeColor}`}>
            {grade}
          </span>
        </div>
      </div>

      {/* Summary */}
      <p className="text-slate-300 text-sm leading-relaxed">{narrative.summary}</p>

      {/* Risks + Positives */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div>
          <p className="text-xs font-semibold text-red-400 uppercase tracking-wide mb-2">Key Risks</p>
          <ul className="space-y-1">
            {narrative.key_risks.map((r, i) => (
              <li key={i} className="flex gap-2 text-sm text-slate-300">
                <span className="text-red-400 mt-0.5 shrink-0">▲</span>
                <span>{r}</span>
              </li>
            ))}
          </ul>
        </div>
        <div>
          <p className="text-xs font-semibold text-emerald-400 uppercase tracking-wide mb-2">Positives</p>
          <ul className="space-y-1">
            {narrative.key_positives.map((p, i) => (
              <li key={i} className="flex gap-2 text-sm text-slate-300">
                <span className="text-emerald-400 mt-0.5 shrink-0">✓</span>
                <span>{p}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>

      {/* Negotiation angle */}
      {narrative.negotiation_angle && (
        <div className="bg-slate-700/50 border border-slate-600 rounded-xl px-4 py-3">
          <p className="text-xs text-amber-400 font-semibold uppercase tracking-wide mb-1">Negotiation Angle</p>
          <p className="text-sm text-slate-200">{narrative.negotiation_angle}</p>
        </div>
      )}

      <p className="text-xs text-slate-500">
        Generated by Claude (subscription) · {narrative.generated_by}
      </p>
    </div>
  );
}
