import { NarrativeData } from '../types/analysis';
import { useLanguage } from '../contexts/LanguageContext';

interface Props {
  narrative: NarrativeData;
  grade: string;
  composite: number;
}

const GRADE_CONFIG: Record<string, { bg: string; text: string; border: string }> = {
  'Excellent buy':          { bg: 'bg-emerald-50', text: 'text-emerald-700', border: 'border-emerald-200' },
  'Good buy':               { bg: 'bg-green-50',   text: 'text-green-700',   border: 'border-green-200' },
  'Proceed with caution':   { bg: 'bg-amber-50',   text: 'text-amber-700',   border: 'border-amber-200' },
  'High risk — reconsider': { bg: 'bg-red-50',     text: 'text-red-700',     border: 'border-red-200' },
};

export default function NarrativeCard({ narrative, grade, composite }: Props) {
  const { t } = useLanguage()
  const cfg = GRADE_CONFIG[grade] ?? { bg: 'bg-stone-50', text: 'text-stone-700', border: 'border-stone-200' };
  const gradeLabel = (t.sections.narrative.grades as Record<string, string>)[grade] ?? grade;

  return (
    <div className="card p-6 space-y-5">
      {/* Header */}
      <div className="flex items-start justify-between gap-4">
        <div className="flex-1">
          <p className="text-xs font-medium uppercase tracking-widest mb-2" style={{ color: 'var(--accent)' }}>
            AI Verdict
          </p>
          <h2 className="font-display text-xl font-semibold leading-snug" style={{ color: 'var(--text-main)' }}>
            {narrative.verdict}
          </h2>
        </div>
        <div className="flex flex-col items-center shrink-0">
          <span className="score-number text-5xl font-bold">{composite}</span>
          <span className={`text-xs font-semibold px-3 py-1 rounded-full mt-2 border ${cfg.bg} ${cfg.text} ${cfg.border}`}>
            {gradeLabel}
          </span>
        </div>
      </div>

      {/* Summary */}
      <p className="text-sm leading-relaxed" style={{ color: 'var(--text-sub)' }}>{narrative.summary}</p>

      {/* Risks + Positives */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div>
          <p className="text-xs font-semibold text-red-600 uppercase tracking-wide mb-2">{t.sections.narrative.risks}</p>
          <ul className="space-y-1.5">
            {narrative.key_risks.map((r, i) => (
              <li key={i} className="flex gap-2 text-sm" style={{ color: 'var(--text-sub)' }}>
                <span className="text-red-500 shrink-0 mt-0.5">▲</span>
                <span>{r}</span>
              </li>
            ))}
          </ul>
        </div>
        <div>
          <p className="text-xs font-semibold text-emerald-600 uppercase tracking-wide mb-2">{t.sections.narrative.positives}</p>
          <ul className="space-y-1.5">
            {narrative.key_positives.map((p, i) => (
              <li key={i} className="flex gap-2 text-sm" style={{ color: 'var(--text-sub)' }}>
                <span className="text-emerald-500 shrink-0 mt-0.5">✓</span>
                <span>{p}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>

      {/* Negotiation angle */}
      {narrative.negotiation_angle && (
        <div className="bg-amber-50 border border-amber-200 rounded-xl px-4 py-3">
          <p className="text-xs font-semibold text-amber-700 uppercase tracking-wide mb-1">{t.sections.narrative.negotiation}</p>
          <p className="text-sm text-amber-800">{narrative.negotiation_angle}</p>
        </div>
      )}

      <p className="text-xs" style={{ color: 'var(--text-muted)' }}>
        Generated by Claude AI · {narrative.generated_by}
      </p>
    </div>
  );
}
